import cron from "node-cron";
import Debate from "../models/debate.model.js";
import { generateDebateTopic } from "../services/ai.service.js";
import { AUTO_DEBATE_CONFIG } from "../config/autoDebate.config.js";

const DAY_MS = 24 * 60 * 60 * 1000;

// Unique numeric id for the schema's `id` field (frontend debates set their own).
const nextId = (offset) => Date.now() + offset;

// Has enough time passed since the last auto debate of this duration?
async function isDue({ label, everyDays }) {
  const last = await Debate.findOne({ autoGenerated: true, duration: label })
    .sort({ createdAt: -1 })
    .select("createdAt");

  if (!last) return true;
  return Date.now() - last.createdAt.getTime() >= everyDays * DAY_MS;
}

async function createBatch({ label, days, count }) {
  for (let i = 0; i < count; i++) {
    try {
      const { name, description } = await generateDebateTopic();

      await Debate.create({
        id: nextId(i),
        name,
        description,
        duration: label,
        user: "AI Community",
        autoGenerated: true,
        expiresAt: new Date(Date.now() + days * DAY_MS),
      });

      console.log(`🤖 Generated ${label} debate: "${name}"`);
    } catch (err) {
      console.error(`❌ Failed to generate ${label} debate:`, err.message);
    }
  }
}

async function runGenerator() {
  for (const duration of AUTO_DEBATE_CONFIG.durations) {
    if (await isDue(duration)) await createBatch(duration);
  }
}

// Tick every day at 09:00. The per-duration interval guard prevents duplicates,
// so restarts or extra ticks are safe.
cron.schedule("0 9 * * *", runGenerator);

// Also run shortly after boot so a fresh server isn't empty (guard still applies).
setTimeout(() => runGenerator().catch((e) => console.error(e.message)), 10_000);
